FROM mammouth.arkhn.com/arkhn/python-base:oracle11

WORKDIR /app

COPY requirements/requirements-base.txt  /app/requirements-base.txt
COPY requirements/requirements-oracle.txt  /app/requirements.txt
RUN pip install -r requirements.txt --src /usr/local/src

COPY pagai /app/pagai
COPY start.sh /app
COPY uwsgi.ini /app

ENV JOBLIB_MULTIPROCESSING=0

CMD ["./start.sh"] 
